@startuml
!$Namf_Communication_AMFStatusChangeSubscribeModfy = "#green"
!$Namf_Communication_AMFStatusChangeUnSubscribe = "#green"
!$Namf_Communication_CancelRelocateUEContext = "#green"
!$Namf_Communication_CreateUEContext = "#gray"
!$Namf_Communication_EBIAssignment = "#green"
!$Namf_Communication_RegistrationStatusUpdate = "#green"
!$Namf_Communication_ReleaseUEContext = "#green"
!$Namf_Communication_RelocateUEContext = "#green"
!$Namf_Communication_UEContextTransfer = "#green"
!$Namf_Communication_N1N2MessageUnSubscribe = "#green"
!$Namf_Communication_N1N2MessageTransfer = "#green"
!$Namf_Communication_N1N2MessageSubscribe = "#green"
!$Namf_Communication_NonUeN2InfoUnSubscribe = "#green"
!$Namf_Communication_NonUeN2MessageTransfer = "#green"
!$Namf_Communication_NonUeN2InfoSubscribe = "#green"
!$Namf_Communication_AMFStatusChangeSubscribe = "#green"
@enduml
