@startuml SFC initiated by trusted AF with application identifiers
!include /home/puml/common.puml
' !startsub ALL

' Uses:
'   TS23502_PCF_Initiated_SM_Policy_Association_Modification
'   TS23502_N4_Session_Modification
' Used by:

!$Nbsf_Management = %load_json("/home/vars/Nbsf_Management.json")
!$Npcf_SMPolicyControl = %load_json("/home/vars/Npcf_SMPolicyControl.json")
!$Nsmf_PDUSession = %load_json("/home/vars/Nsmf_PDUSession.json")
!$Npcf_PolicyAuthorization = %load_json("/home/vars/Npcf_PolicyAuthorization.json")

participant UPF as UPF order 1
participant SMF as SMF order 2
participant PCF as PCF order 3
participant UDR as UDR order 4
participant NEF as NEF order 5
' participant BSF as BSF order 6
participant AF as AF order 7

' Assign default colors to the Operations is they are not assigned in the vars file
!$Nbsf_Management_GetPCFBindings ?= $color($Nbsf_Management.Nbsf_Management_GetPCFBindings)
!$Npcf_SMPolicyControl_CreateSMPolicy ?= $color($Npcf_SMPolicyControl.Npcf_SMPolicyControl_CreateSMPolicy)
!$Npcf_SMPolicyControl_UpdateSMPolicy ?= $color($Npcf_SMPolicyControl.Npcf_SMPolicyControl_UpdateSMPolicy)
!$Npcf_SMPolicyControl_DeleteSMPolicy ?= $color($Npcf_SMPolicyControl.Npcf_SMPolicyControl_DeleteSMPolicy)
!$Npcf_SMPolicyControl_UpdateNotify ?= $color($Npcf_SMPolicyControl.Npcf_SMPolicyControl_UpdateNotify)

!$Npcf_PolicyAuthorization_Create ?= $color($Npcf_PolicyAuthorization.Npcf_PolicyAuthorization_PostAppSessions)

autonumber

!startsub AF_PCF
' AF <-[$Nbsf_Management_GetPCFBindings]- BSF : Nbsf_Management_GetPCFBindings request
' AF -[$Nbsf_Management_GetPCFBindings]-> BSF : Nbsf_Management_GetPCFBindings response
AF -[$Npcf_PolicyAuthorization_Create]> PCF : Npcf_PolicyAuthorization_Create/Update/Delete request
!endsub

group PCF initiated SM Policy Association Modification
!includesub /home/puml/TS23502_PCF_Initiated_SM_Policy_Association_Modification.puml!Policy_Management
end

group PFD Retrieval by the SMF
!includesub /home/puml/TS23502_PFD_Retrieval_SMF.puml!ALL
end

group PFD management in the UPF
!includesub /home/puml/TS23502_PFD_Management_UPF.puml!ALL
end

group N4 Session Modification
!includesub /home/puml/TS23502_N4_Session_Modification.puml!ALL
end

!includesub /home/puml/Legend.puml!ALL
' !endsub
@enduml