@startuml 

title Network-initiated Deregistration

!include /home/puml/common.puml
!$Nudm_UECM = %load_json("/home/vars/Nudm_UECM.json")
!$Nudm_SDM = %load_json("/home/vars/Nudm_SDM.json")

' Uses:
'   TS23502_AMF_Initiated_AM_Policy_Association_Termination.puml

participant UE as UE
participant "R(AN)" as RAN
participant AMF as AMF
participant PCF as PCF
participant SMF as SMF
participant UPF as UPF
participant UDM as UDM

' Assign default colors to the Operations is they are not assigned in the vars file
!$Nudm_UECM_DeregistrationNotification ?= $color($Nudm_UECM.Nudm_UECM_DeregistrationNotification)
!$Nudm_SDM_Unsubscribe ?= $color($Nudm_SDM.Nudm_SDM_Unsubscribe)

UDM -[$Nudm_UECM_DeregistrationNotification]-> AMF : 1. Nudm_UECM_DeregistrationNotification
AMF --> UE : 2. De-registration Request
UDM <-[$Nudm_UECM_DeregistrationNotification]- AMF : 3. Nudm_UECM_DeregistrationNotification Ack
AMF -[$Nudm_SDM_Unsubscribe]-> UDM : 3a. Nudm_SDM_Unsubscribe
' ref over AMF,PCF,SMF,UPF
'     4. Step 2 ~ step 5 of UE initiated De-registration [[file://TS23502_UEInitiated_Deregistration.puml link]]
' end ref
group 4. Step 2 ~ step 5 of UE initiated De-registration
!includesub /home/puml/TS23502_UEInitiated_Deregistration.puml!VARS
!includesub /home/puml/TS23502_UEInitiated_Deregistration.puml!STEP2to5
end
ref over AMF,PCF
    5. AMF-initiated AM Policy Association Termination [[file://TS23502_AMF_Initiated_AM_Policy_Association_Termination.puml link]]
end ref
UE --> AMF : De-registration Accept
AMF <--> RAN : 7. Signalling Connection Release
RAN <--> UE : 7. Signalling Connection Release
@enduml