@startuml N4 Session Modification
!include /home/puml/common.puml
!startsub ALL

' Uses:

' Used by:

participant UPF as UPF
participant SMF as SMF

ref over SMF
    1. Trigger to modify PDU session
end ref

autonumber 2
SMF -> UPF : N4 Session Modification request
SMF <- UPF : N4 Session Modification response

ref over SMF
    4. Interaction with other network function
end ref
!endsub
@enduml