@startuml SMF initiated SM Policy Association Modification

!include /home/common.puml
!$Npcf_SMPolicyControl = %load_json("/home/vars/Npcf_SMPolicyControl.json")

' Used by:
'   TS23502_UE_Triggered_Service_Request.puml
'   TS23502_UERequested_PDU_Session_Establishment_NonRoaming_And_Roaming_With_Local_Breakout.puml

' Uses:
'   TS23502_Initial_Spending_Limit_Report_Retrieval.puml

participant AMF as AMF
participant UPF as UPF
participant SMF as SMF
participant PCF as PCF
participant UDR as UDR
participant AF as AF
participant CHF as CHF

' Assign default colors to the Operations is they are not assigned in the vars file
!$Npcf_SMPolicyControl_Update ?= $color($Npcf_SMPolicyControl.Npcf_SMPolicyControl_Update)

SMF -[$Npcf_SMPolicyControl_Update]> PCF : 1. Npcf_SMPolicyControl_Update request

ref over PCF,UDR,AF,CHF
    2. Spending Limit Report Retrieval [[file://TS23502_Initial_Spending_Limit_Report_Retrieval.puml link]]
end ref

note over PCF
    3. Policy Decision
end note

SMF <[$Npcf_SMPolicyControl_Update]- PCF : 4. Npcf_SMPolicyControl_Update response

@enduml