@startuml General Registration

!include /home/puml/common.puml
!$Namf_Communication = %load_json("/home/vars/Namf_Communication.json")

' Uses:
'

participant UE as UE
participant "R(AN)" as RAN
participant "New AMF" as NAMF
participant "Old AMF" as OAMF
participant EIR as EIR
participant "N3IWF/TNGF/W-AGF" as WGF
participant PCF as PCF
participant SMF as SMF
participant AUSF as AUSF
participant UDM as UDM

' Assign default colors to the Operations is they are not assigned in the vars file
!$Namf_Communication_UEContextTransfer_Color = $color($Namf_Communication.Namf_Communication_UEContextTransfer)
!$Namf_Communication_RegistrationStatusUpdate_Color ?= $color($Namf_Communication.Namf_Communication_RegistrationStatusUpdate)
!$N5geir_EquipmentIdentityCheck_Get_Color ?= $color($Namf_Communication.N5geir_EquipmentIdentityCheck_Get)
!$Nudm_UECM_Registration_Color ?= $color($Namf_Communication.Nudm_UECM_Registration)
!$Nudm_SDM_Get_Color ?= $color($Namf_Communication.Nudm_SDM_Get)
!$Nudm_SDM_Subscribe_Color ?= $color($Namf_Communication.Nudm_SDM_Subscribe)
!$Nudm_UECM_DeregistrationNotification_Color ?= $color($Namf_Communication.Nudm_UECM_DeregistrationNotification)
!$Nudm_SDM_Unsubscribe_Color ?= $color($Namf_Communication.Nudm_SDM_Unsubscribe)
!$Nsmf_PDUSession_UpdateSMContext_Color ?= $color($Namf_Communication.Nsmf_PDUSession_UpdateSMContext)
!$Nsmf_PDUSession_ReleaseSMContext_Color ?= $color($Namf_Communication.Nsmf_PDUSession_ReleaseSMContext)
!$Nudm_UECM_Registration_Color ?= $color($Namf_Communication.Nudm_UECM_Registration)
!$Nudm_UECM_DeregistrationNotify_Color ?= $color($Namf_Communication.Nudm_UECM_DeregistrationNotify)
!$Nudm_SDM_Unsubscribe_Color ?= $color($Namf_Communication.Nudm_SDM_Unsubscribe)
!$Nudm_SDM_Info_Color ?= $color($Namf_Communication.Nudm_SDM_Info)
!$Nudm_UECM_Update_Color ?= $color($Namf_Communication.Nudm_UECM_Update)
!$UE_Context_Modification_Color ?= $color($Namf_Communication.UE_Context_Modification)

' Requests go from left to right
' Responses go from right to left
autonumber
UE -> RAN : Registration Request

ref over RAN
    2. AMF selection
end ref

autonumber 3
RAN -> NAMF : Registration Request **$Namf_Communication.Namf_Communication_UEContextTransfer**
NAMF -[$Namf_Communication_UEContextTransfer_Color]-> OAMF : Namf_Communication_UEContextTransfer
NAMF <-[$Namf_Communication_UEContextTransfer_Color]- OAMF : Namf_Communication_UEContextTransfer response
NAMF --> UE : Identity Request
NAMF <-- UE : Identity Response

ref over NAMF
    8. AUSF selection
end ref

ref over UE, UDM
    9. Authentication/Security
end ref

autonumber 10
NAMF -[$Namf_Communication_RegistrationStatusUpdate_Color]-> OAMF : Namf_Communication_RegistrationStatusUpdate
NAMF <--> UE : Identity Request/Response
NAMF -[$N5geir_EquipmentIdentityCheck_Get_Color]-> EIR : N5g-eir_EquipmentIdentityCheck_Get
autonumber stop
NAMF <-[$N5geir_EquipmentIdentityCheck_Get_Color]- EIR

ref over NAMF
    13. UDM selection
end ref

autonumber 14.0
NAMF -[$Nudm_UECM_Registration_Color]-> UDM : Nudm_UECM_Registration
autonumber stop
NAMF <-[$Nudm_UECM_Registration_Color]- UDM
autonumber resume
NAMF -[$Nudm_SDM_Get_Color]-> UDM : Nudm_SDM_Get
autonumber stop
NAMF <-[$Nudm_SDM_Get_Color]- UDM
autonumber resume
NAMF -[$Nudm_SDM_Subscribe_Color]-> UDM : Nudm_SDM_Subscribe
UDM -[$Nudm_UECM_DeregistrationNotification_Color]-> OAMF : Nudm_UECM_DeregistrationNotification
UDM <-[$Nudm_SDM_Unsubscribe_Color]- OAMF : Nudm_SDM_Unsubscribe

autonumber stop
ref over NAMF
    15. PCF selection
end ref

autonumber 16
NAMF <--> PCF : AM Policy Association Establishment/Modification
NAMF -[$Nsmf_PDUSession_UpdateSMContext_Color]-> SMF : Nsmf_PDUSession_UpdateSMContext
autonumber stop
NAMF -[$Nsmf_PDUSession_ReleaseSMContext_Color]-> SMF : Nsmf_PDUSession_ReleaseSMContext
autonumber resume
NAMF -[$UE_Context_Modification_Color]-> WGF : UE Context Modification Request
NAMF <-[$UE_Context_Modification_Color]- WGF : UE Context Modification Response
autonumber 19.1
NAMF -[$Nudm_UECM_Registration_Color]-> UDM : Nudm_UECM_Registration
UDM -[$Nudm_UECM_DeregistrationNotify_Color]-> OAMF : Nudm_UECM_DeregistrationNotify
UDM <-[$Nudm_SDM_Unsubscribe_Color]- OAMF : Nudm_SDM_Unsubscribe
autonumber 21.0
NAMF -> UE :  Registration Accept
NAMF <--> PCF :  UE Policy Association Establishment
autonumber 22
NAMF <-- UE :  Registration Complete
autonumber 23.0
NAMF -[$Nudm_SDM_Info_Color]-> UDM : Nudm_SDM_Info
autonumber stop
NAMF <-[$Nudm_SDM_Info_Color]- UDM
autonumber resume
NAMF --> RAN : N2 message
autonumber 24
NAMF -[$Nudm_UECM_Update_Color]-> UDM : Nudm_UECM_Update
autonumber stop
NAMF <-[$Nudm_UECM_Update_Color]- UDM
autonumber resume

ref over UE, NAMF
    25.  Network Slice-Specific Authentication and Authorization 
end ref
@enduml