@startuml SM Policy Association Establishment

!include /home/puml/common.puml
!startsub ALL
!$Nudr_DM = %load_json("/home/vars/Nudr_DM.json")
!$Npcf_AMPolicyControl = %load_json("/home/vars/Npcf_AMPolicyControl.json")

' Used by:
'   TS23502_UERequested_PDU_Session_Establishment_NonRoaming_And_Roaming_With_Local_Breakout.puml

participant AMF as AMF
participant "H-PCF" as HPCF
participant UDR as UDR

' Assign default colors to the Operations is they are not assigned in the vars file
!$Nudr_DM_Notify ?= $color($Nudr_DM.Nudr_DM_Notify)
!$Npcf_AMPolicyControl_UpdateNotify ?= $color($Npcf_AMPolicyControl.Npcf_AMPolicyControl_UpdateNotify)

note over UDR
    1. Plociy Data Removed
end note
UDR -[$Nudr_DM_Notify]-> HPCF : 2. Nudr_DM_Notify Request
UDR <-[$Nudr_DM_Notify]- HPCF : 3. Nudr_DM_Notify Response
HPCF -[$Npcf_AMPolicyControl_UpdateNotify]-> AMF : 4. Npcf_AMPolicyControl_UpdateNotify Request
HPCF <-[$Npcf_AMPolicyControl_UpdateNotify]- AMF : 5. Npcf_AMPolicyControl_UpdateNotify Response
note over AMF
    6. Removes the Access and Mobility Control Policy
end note
!endsub
@enduml