@startuml UE-requested PDU Session Establishment for non-roaming and roaming with local breakout

!include /home/common.puml
' TODO: include pcf services variables

' Uses:
'   TS23502_PDU_Session_Establishment_Authentication_Authorization_DNAAA_Server.puml
'   TS23502_SMF_Initiated_SM_Policy_Association_Modification.puml
'   TS23502_SM_Policy_Association_Establishment.puml

!$DEFAULT_COLOR = "#gray"

participant UE as UE
participant "R(AN)" as RAN
participant AMF as AMF
participant UPF as UPF
participant SMF as SMF
participant PCF as PCF
participant UDM as UDM
participant DN as DN

' Assign default colors to the Operations is they are not assigned in the vars file
!$Nsmf_PDUSession_CreateSMContext ?= $DEFAULT_COLOR
!$Namf_Communication_N1N2MessageTransfer ?= $DEFAULT_COLOR
!$Nsmf_PDUSession_UpdateSMContext ?= $DEFAULT_COLOR
!$Nsmf_PDUSession_SMContextStatusNotify ?= $DEFAULT_COLOR

UE -> AMF : 1. PDU Session Establishment Request
ref over AMF
    2. AMF Selection
end ref
AMF -[$Nsmf_PDUSession_CreateSMContext]> SMF : 3. Nsmf_PDUSession_CreateSMContext Request
ref over SMF,PCF,UDM
    4a-4b Registration/Subscription retrieval/Subscription updates
end ref
AMF <[$Nsmf_PDUSession_CreateSMContext]- SMF : 5. Nsmf_PDUSession_CreateSMContext Response
ref over UE,RAN,AMF,UPF,SMF,PCF,UDM,DN
    6. PDU Session authentication/authorization [[file://TS23502_PDU_Session_Establishment_Authentication_Authorization_DNAAA_Server.puml link]]
end ref
note over PCF
    7a. PCF selection
end note
ref over SMF,PCF
    7b. SM Policy Association Establishment [[file://TS23502_SM_Policy_Association_Establishment.puml link]] or SMF initiated SM Policy Association Modification [[file://TS23502_SMF_Initiated_SM_Policy_Association_Modification.puml link]]
end ref
note over SMF
    8. UPF selection
end note
ref over SMF,PCF
    9. SMF initiated SM Policy Association Modification [[file://TS23502_SMF_Initiated_SM_Policy_Association_Modification.puml link]]
end ref
SMF --> UPF : 10a.  N4 Session Establishment/Modification Request
SMF <-- UPF : 10b.  N4 Session Establishment/Modification Response
SMF -[$Namf_Communication_N1N2MessageTransfer]> AMF : 11. Namf_Communication_N1N2MessageTransfer
SMF <[$Namf_Communication_N1N2MessageTransfer]- AMF
AMF -> RAN : 12. N2 PDU Session Request (NAS msg)
RAN <-> UE : 13. AN-specific resource setup (PDU Session Establishment Accept)
RAN -> AMF : 14. N2 PDU Session Request Ack
UE --> UPF : First Uplink Data
AMF -[$Nsmf_PDUSession_UpdateSMContext]> SMF : 15. Nsmf_PDUSession_UpdateSMContext Request
SMF -> UPF : 16a. N4 Session Modification Request
UPF --> UE : First Downlink Data
SMF <- UPF : 16b. N4 Session Modification Response
AMF <[$Nsmf_PDUSession_UpdateSMContext]- SMF : 17. Nsmf_PDUSession_UpdateSMContext Response
SMF -[$Nsmf_PDUSession_SMContextStatusNotify]-> AMF : 18. Nsmf_PDUSession_SMContextStatusNotify
SMF --> UPF
UPF --> UE : 19. IPv6 Address Configuration
ref over SMF,PCF,UDM
    19. Unsubscription/Deregistration
end ref
@enduml