@startuml PFD Retrieval by the SMF
!include /home/puml/common.puml
!startsub ALL

' Uses:

' Used by:

!$Nnef_PFDmanagement = %load_json("/home/vars/Nnef_PFDmanagement.json")
!$Nudr_DataRepository = %load_json("/home/vars/Nudr_DataRepository.json")
!$Nudr_DM = %load_json("/home/vars/Nudr_DM.json")

participant SMF as SMF
participant NEF as "NEF(PFDF)"
participant UDR as UDR

' Assign default colors to the Operations is they are not assigned in the vars file
!$Nnef_PFDmanagement_IndAppFetch ?= $color($Nnef_PFDmanagement.Nnef_PFDmanagement_IndAppFetch)
!$Nudr_DM_Query ?= $color($Nudr_DM.Nudr_DM_Query)
!$Nudr_DM_Create ?= $color($Nudr_DM.Nudr_DM_Create)
!$Nudr_DataRepository_ReadPFDData ?= $color($Nudr_DataRepository.Nudr_DataRepository_ReadPFDData)

autonumber

SMF -[$Nnef_PFDmanagement_IndAppFetch]> NEF : Nnef_PFDmanagement_IndAppFetch request

NEF -[$Nudr_DataRepository_ReadPFDData]> UDR : Nudr_DataRepository_ReadPFDData request
NEF <[$Nudr_DataRepository_ReadPFDData]- UDR : Nudr_DataRepository_ReadPFDData response
SMF <[$Nnef_PFDmanagement_IndAppFetch]- NEF : Nnef_PFDmanagement_IndAppFetch response
!endsub
@enduml