@startuml General Registration

!include /home/puml/common.puml
!$Namf_Communication = %load_json("/home/vars/Namf_Communication.json")
!$Nudm_UECM = %load_json("/home/vars/Nudm_UECM.json")
!$FgEir_EquipmentIdentityCheck = %load_json("/home/vars/5gEir_EquipmentIdentityCheck.json")
!$Nudm_SDM = %load_json("/home/vars/Nudm_SDM.json")
!$Nsmf_PDUSession = %load_json("/home/vars/Nsmf_PDUSession.json")

' Uses:
'

participant UE as UE
participant "R(AN)" as RAN
participant "New AMF" as NAMF
participant "Old AMF" as OAMF
participant EIR as EIR
participant "N3IWF/TNGF/W-AGF" as WGF
participant PCF as PCF
participant SMF as SMF
participant AUSF as AUSF
participant UDM as UDM

' Assign default colors to the Operations is they are not assigned in the vars file
!$Namf_Communication_UEContextTransfer = $color($Namf_Communication.Namf_Communication_UEContextTransfer)
!$Namf_Communication_RegistrationStatusUpdate ?= $color($Namf_Communication.Namf_Communication_RegistrationStatusUpdate)
!$N5gEir_EquipmentIdentityCheck_GetEquipmentStatus ?= $color($FgEir_EquipmentIdentityCheck.5gEir_EquipmentIdentityCheck_GetEquipmentStatus)
!$Nudm_UECM_Registration ?= $color($Nudm_UECM.Nudm_UECM_Registration)
!$Nudm_SDM_GetDataSets ?= $color($Nudm_SDM.Nudm_SDM_GetDataSets)
!$Nudm_SDM_Subscribe ?= $color($Nudm_SDM.Nudm_SDM_Subscribe)
!$Nudm_UECM_DeregistrationNotification ?= $color($Nudm_UECM.Nudm_UECM_DeregistrationNotification)
!$Nudm_SDM_Unsubscribe ?= $color($Nudm_SDM.Nudm_SDM_Unsubscribe)
!$Nsmf_PDUSession_UpdateSMContext ?= $color($Nsmf_PDUSession.Nsmf_PDUSession_UpdateSMContext)
!$Nsmf_PDUSession_ReleaseSMContext ?= $color($Nsmf_PDUSession.Nsmf_PDUSession_ReleaseSMContext)
!$Nudm_UECM_Registration ?= $color($Nudm_UECM.Nudm_UECM_Registration)
!$Nudm_UECM_DeregistrationNotify ?= $color($Nudm_UECM.Nudm_UECM_DeregistrationNotify)
!$Nudm_SDM_Unsubscribe ?= $color($Nudm_SDM.Nudm_SDM_Unsubscribe)
!$Nudm_SDM_UpdateSORInfo ?= $color($Nudm_SDM.Nudm_SDM_UpdateSORInfo)
!$Nudm_UECM_Update ?= $color($Nudm_UECM.Nudm_UECM_Update)
!$UE_Context_Modification ?= $color($Namf_Communication.UE_Context_Modification)

' Requests go from left to right
' Responses go from right to left
autonumber
UE -> RAN : Registration Request

ref over RAN
    2. AMF selection
end ref

autonumber 3
RAN -> NAMF : Registration Request
NAMF -[$Namf_Communication_UEContextTransfer]-> OAMF : Namf_Communication_UEContextTransfer
NAMF <-[$Namf_Communication_UEContextTransfer]- OAMF : Namf_Communication_UEContextTransfer response
NAMF --> UE : Identity Request
NAMF <-- UE : Identity Response

ref over NAMF
    8. AUSF selection
end ref

ref over UE, UDM
    9. Authentication/Security
end ref

autonumber 10
NAMF -[$Namf_Communication_RegistrationStatusUpdate]-> OAMF : Namf_Communication_RegistrationStatusUpdate
NAMF <--> UE : Identity Request/Response
NAMF -[$N5gEir_EquipmentIdentityCheck_GetEquipmentStatus]-> EIR : N5g-eir_EquipmentIdentityCheck_GetEquipmentStatus
autonumber stop
NAMF <-[$N5gEir_EquipmentIdentityCheck_GetEquipmentStatus]- EIR

ref over NAMF
    13. UDM selection
end ref

autonumber 14.0
NAMF -[$Nudm_UECM_Registration]-> UDM : Nudm_UECM_Registration
autonumber stop
NAMF <-[$Nudm_UECM_Registration]- UDM
autonumber resume
NAMF -[$Nudm_SDM_GetDataSets]-> UDM : Nudm_SDM_GetDataSets
autonumber stop
NAMF <-[$Nudm_SDM_GetDataSets]- UDM
autonumber resume
NAMF -[$Nudm_SDM_Subscribe]-> UDM : Nudm_SDM_Subscribe
UDM -[$Nudm_UECM_DeregistrationNotification]-> OAMF : Nudm_UECM_DeregistrationNotification
UDM <-[$Nudm_SDM_Unsubscribe]- OAMF : Nudm_SDM_Unsubscribe

autonumber stop
ref over NAMF
    15. PCF selection
end ref

autonumber 16
NAMF <--> PCF : AM Policy Association Establishment/Modification
NAMF -[$Nsmf_PDUSession_UpdateSMContext]-> SMF : Nsmf_PDUSession_UpdateSMContext
autonumber stop
NAMF -[$Nsmf_PDUSession_ReleaseSMContext]-> SMF : Nsmf_PDUSession_ReleaseSMContext
autonumber resume
NAMF -[$UE_Context_Modification]-> WGF : UE Context Modification Request
NAMF <-[$UE_Context_Modification]- WGF : UE Context Modification Response
autonumber 19.1
NAMF -[$Nudm_UECM_Registration]-> UDM : Nudm_UECM_Registration
UDM -[$Nudm_UECM_DeregistrationNotify]-> OAMF : Nudm_UECM_DeregistrationNotify
UDM <-[$Nudm_SDM_Unsubscribe]- OAMF : Nudm_SDM_Unsubscribe
autonumber 21.0
NAMF -> UE :  Registration Accept
NAMF <--> PCF :  UE Policy Association Establishment
autonumber 22
NAMF <-- UE :  Registration Complete
autonumber 23.0
NAMF -[$Nudm_SDM_UpdateSORInfo]-> UDM : Nudm_SDM_UpdateSORInfo
autonumber stop
NAMF <-[$Nudm_SDM_UpdateSORInfo]- UDM
autonumber resume
NAMF --> RAN : N2 message
autonumber 24
NAMF -[$Nudm_UECM_Update]-> UDM : Nudm_UECM_Update
autonumber stop
NAMF <-[$Nudm_UECM_Update]- UDM
autonumber resume

ref over UE, NAMF
    25.  Network Slice-Specific Authentication and Authorization 
end ref
@enduml