@startuml Network Triggered Service Request

!include /home/puml/common.puml
!$Namf_Communication = %load_json("/home/vars/Namf_Communication.json")

' Uses:
'   TS23502_UERequested_PDU_Session_Establishment_NonRoaming_And_Roaming_With_Local_Breakout.puml

participant UE as UE
participant "R(AN)" as RAN
participant AMF as AMF
participant SMF as SMF
participant UPF as UPF
participant DN as DN

' Assign default colors to the Operations is they are not assigned in the vars file
!$Namf_Communication_N1N2MessageTransfer ?= $color($Namf_Communication.Namf_Communication_N1N2MessageTransfer)
!$Namf_Communication_N1N2TransferFailure ?= $color($Namf_Communication.Namf_Communication_N1N2TransferFailure)

DN --> UPF : 1. Downlink data
UPF --> SMF : 2a. Data Modification
UPF <-- SMF : 2b. Data Modification Ack
UPF --> SMF : 2c. Downlink data
SMF -[$Namf_Communication_N1N2MessageTransfer]-> AMF : 3a. Namf_Communication_N1N2MessageTransfer
SMF <-[$Namf_Communication_N1N2MessageTransfer]- AMF : 3b. Namf_Communication_N1N2MessageTransfer Response
SMF --> UPF : 3c. Failure indication
ref over UE,RAN,AMF
    4a. UP reactivation (Connected)
end ref
AMF --> RAN : 4b. Paging
RAN --> UE : 4b. Paging
AMF --> UE : 4c. NAS Notification
AMF -[$Namf_Communication_N1N2TransferFailure]-> SMF : 5. Namf_Communication_N1N2TransferFailure Notification
group UE-requested PDU Session Establishment for non-roaming and roaming with local breakout
!includesub /home/puml/TS23502_UERequested_PDU_Session_Establishment_NonRoaming_And_Roaming_With_Local_Breakout.puml!ALL
end
UPF --> RAN : 7. Downlink data
RAN --> UE : 7. Downlink data

@enduml