@startuml PFD management in the UPF
!include /home/puml/common.puml
!startsub ALL

' Uses:

' Used by:

participant SMF as SMF
participant UPF as UPF

note over SMF
    1. Trigger to provision or remove the set of PFDs belonging to an Application Identifier
end note

autonumber 2
SMF -> UPF : PFD management request
SMF <- UPF : PFD management response
!endsub
@enduml