@startuml AMF-initiated AM Policy Association Termination

!include /home/common.puml
!startsub ALL
!$Npcf_AMPolicyControl = %load_json("/home/vars/Npcf_AMPolicyControl.json")

' Used
'   TS23502_UEInitiated_Deregistration.puml
'   TS23502_NetworkInitiated_Deregistration.puml

participant AMF as AMF
participant "V-PCF" as VPCF
participant "H-PCF" as HPCF

' Assign default colors to the Operations is they are not assigned in the vars file
!$Npcf_AMPolicyControl_Delete ?= $color($Npcf_AMPolicyControl.Npcf_AMPolicyControl_Delete)

note over AMF
    1. Decision to terminate the Policy Association
end note

AMF -[$Npcf_AMPolicyControl_Delete]-> HPCF : 2. Npcf_AMPolicyControl_Delete
AMF <-[$Npcf_AMPolicyControl_Delete]- HPCF : 3. Npcf_AMPolicyControl_Delete response

note over AMF
    4. Remove the Access and Mobility Control Policy
end note
!endsub
@enduml