@startuml 

title UE-requested PDU Session Establishment for non-roaming and roaming with local breakout

!include /home/puml/common.puml
!startsub ALL
!$Namf_Communication = %load_json("/home/vars/Namf_Communication.json")
!$Nsmf_PDUSession = %load_json("/home/vars/Nsmf_PDUSession.json")

' Uses:
'   TS23502_PDU_Session_Establishment_Authentication_Authorization_DNAAA_Server.puml
'   TS23502_SMF_Initiated_SM_Policy_Association_Modification.puml
'   TS23502_SM_Policy_Association_Establishment.puml

participant UE as UE
participant "R(AN)" as RAN
participant AMF as AMF
participant UPF as UPF
participant SMF as SMF
participant PCF as PCF
participant UDM as UDM
participant DN as DN

' Assign default colors to the Operations is they are not assigned in the vars file
!$Nsmf_PDUSession_PostSMContexts ?= $color($Nsmf_PDUSession.Nsmf_PDUSession_PostSMContexts)
!$Namf_Communication_N1N2MessageTransfer ?= $color($Namf_Communication.Namf_Communication_N1N2MessageTransfer)
!$Nsmf_PDUSession_UpdateSMContext ?= $color($Nsmf_PDUSession.Nsmf_PDUSession_UpdateSMContext)
!$Nsmf_PDUSession_SMContextStatusNotify ?= $color($Nsmf_PDUSession.Nsmf_PDUSession_SMContextStatusNotify)

UE -> AMF : 1. PDU Session Establishment Request
note over AMF
    2. AMF Selection
end note
AMF -[$Nsmf_PDUSession_PostSMContexts]> SMF : 3. Nsmf_PDUSession_PostSMContexts Request
ref over SMF,PCF,UDM
    4a-4b Registration/Subscription retrieval/Subscription updates
end ref
AMF <[$Nsmf_PDUSession_PostSMContexts]- SMF : 5. Nsmf_PDUSession_PostSMContexts Response
group PDU Session Establishment authentication or authorization by a DN-AAA server
!includesub /home/puml/TS23502_PDU_Session_Establishment_Authentication_Authorization_DNAAA_Server.puml!ALL
end
note over PCF
    7a. PCF selection
end note
group SM Policy Association Establishment
!includesub /home/puml/TS23502_SM_Policy_Association_Establishment.puml!ALL
end
note over SMF
    8. UPF selection
end note
group SMF initiated SM Policy Association Modification
!includesub /home/puml/TS23502_SMF_Initiated_SM_Policy_Association_Modification.puml!ALL
end
SMF --> UPF : 10a.  N4 Session Establishment/Modification Request
SMF <-- UPF : 10b.  N4 Session Establishment/Modification Response
SMF -[$Namf_Communication_N1N2MessageTransfer]> AMF : 11. Namf_Communication_N1N2MessageTransfer
SMF <[$Namf_Communication_N1N2MessageTransfer]- AMF
AMF -> RAN : 12. N2 PDU Session Request (NAS msg)
RAN <-> UE : 13. AN-specific resource setup (PDU Session Establishment Accept)
RAN -> AMF : 14. N2 PDU Session Request Ack
UE --> UPF : First Uplink Data
AMF -[$Nsmf_PDUSession_UpdateSMContext]> SMF : 15. Nsmf_PDUSession_UpdateSMContext Request
SMF -> UPF : 16a. N4 Session Modification Request
UPF --> UE : First Downlink Data
SMF <- UPF : 16b. N4 Session Modification Response
AMF <[$Nsmf_PDUSession_UpdateSMContext]- SMF : 17. Nsmf_PDUSession_UpdateSMContext Response
SMF -[$Nsmf_PDUSession_SMContextStatusNotify]-> AMF : 18. Nsmf_PDUSession_SMContextStatusNotify
SMF --> UPF
UPF --> UE : 19. IPv6 Address Configuration
ref over SMF,PCF,UDM
    19. Unsubscription/Deregistration
end ref
!endsub
@enduml