@startuml
!include /home/Namf_Communication.puml

Alice -[$AMFStatusChangeSubscribeModfy]> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: Another authentication Response
@enduml