name: Build/Publish Develop Docs 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install Dependencies
        run: |
          pip install mkdocs-material
          pip install plantuml-markdown
          pip install mkdocs-markdownextradata-plugin
          pip install mkdocs-macros-plugin
          pip install mike
      - name: Build Docs Website
        run: mike deploy --push dev